"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteDispositivoController2 = exports.dispositivoPost = exports.AllDispositivosController = void 0;
const Dispositivos_services_1 = require("../application/services/Dispositivos.services");
const myqsl_adapters_1 = require("./adapters/myqsl.adapters");
const getAllDispositivos_controller_1 = require("./controllers/getAllDispositivos.controller");
const mySqlAdapter = new myqsl_adapters_1.MySqlAdapter();
const getAllDispositivos = new Dispositivos_services_1.getAllDispositivosService(mySqlAdapter);
exports.AllDispositivosController = new getAllDispositivos_controller_1.getAllDispositivosController(getAllDispositivos);
const CrearDispositivoService = new Dispositivos_services_1.agregarDispositivo(mySqlAdapter);
exports.dispositivoPost = new getAllDispositivos_controller_1.CrearDispositivo(CrearDispositivoService);
const deleteDispositivooService = new Dispositivos_services_1.deleteDispositivo(mySqlAdapter);
exports.deleteDispositivoController2 = new getAllDispositivos_controller_1.deleteDispositivoController(deleteDispositivooService);
